java -jar ParallelHyperQAP.jar sko42.qap 4
java -jar ParallelHyperQAP.jar sko49.qap 4
java -jar ParallelHyperQAP.jar sko56.qap 4
java -jar ParallelHyperQAP.jar sko64.qap 4
java -jar ParallelHyperQAP.jar sko72.qap 4
java -jar ParallelHyperQAP.jar sko81.qap 4
java -jar ParallelHyperQAP.jar sko90.qap 4
java -jar ParallelHyperQAP.jar sko100e.qap 4
java -jar ParallelHyperQAP.jar sko100f.qap 4
java -jar ParallelHyperQAP.jar ste36a.qap 4
java -jar ParallelHyperQAP.jar ste36b.qap 4
java -jar ParallelHyperQAP.jar tai35a.qap 4
java -jar ParallelHyperQAP.jar tai35b.qap 4
java -jar ParallelHyperQAP.jar tai40a.qap 4
java -jar ParallelHyperQAP.jar tai40b.qap 4
java -jar ParallelHyperQAP.jar tai50a.qap 4
java -jar ParallelHyperQAP.jar tai50b.qap 4
java -jar ParallelHyperQAP.jar tai60a.qap 4
java -jar ParallelHyperQAP.jar tai60b.qap 4
java -jar ParallelHyperQAP.jar tai64c.qap 4
java -jar ParallelHyperQAP.jar tai80a.qap 4
java -jar ParallelHyperQAP.jar tai80b.qap 4
java -jar ParallelHyperQAP.jar tai100a.qap 4
java -jar ParallelHyperQAP.jar tai100b.qap 4
java -jar ParallelHyperQAP.jar tai150b.qap 4
java -jar ParallelHyperQAP.jar tai256c.qap 4
java -jar ParallelHyperQAP.jar tho40.qap 4
java -jar ParallelHyperQAP.jar tho150.qap 4
java -jar ParallelHyperQAP.jar wil50.qap 4
java -jar ParallelHyperQAP.jar wil100.qap 4
