java -jar ParallelHyperQAP.jar bur26a.qap
java -jar ParallelHyperQAP.jar bur26b.qap
java -jar ParallelHyperQAP.jar bur26c.qap
java -jar ParallelHyperQAP.jar bur26d.qap
java -jar ParallelHyperQAP.jar bur26e.qap
java -jar ParallelHyperQAP.jar bur26f.qap
java -jar ParallelHyperQAP.jar bur26g.qap
java -jar ParallelHyperQAP.jar bur26h.qap
java -jar ParallelHyperQAP.jar chr12a.qap
java -jar ParallelHyperQAP.jar chr12b.qap
java -jar ParallelHyperQAP.jar chr12c.qap
java -jar ParallelHyperQAP.jar chr15a.qap
java -jar ParallelHyperQAP.jar chr15b.qap
java -jar ParallelHyperQAP.jar chr15c.qap
java -jar ParallelHyperQAP.jar chr18a.qap
java -jar ParallelHyperQAP.jar chr18b.qap
java -jar ParallelHyperQAP.jar chr20a.qap
java -jar ParallelHyperQAP.jar chr20b.qap
java -jar ParallelHyperQAP.jar chr20c.qap
java -jar ParallelHyperQAP.jar chr22a.qap
java -jar ParallelHyperQAP.jar chr22b.qap
java -jar ParallelHyperQAP.jar chr25a.qap
java -jar ParallelHyperQAP.jar els19.qap
java -jar ParallelHyperQAP.jar esc16a.qap
java -jar ParallelHyperQAP.jar esc16b.qap
java -jar ParallelHyperQAP.jar esc16c.qap
java -jar ParallelHyperQAP.jar esc16d.qap
java -jar ParallelHyperQAP.jar esc16e.qap
java -jar ParallelHyperQAP.jar esc16f.qap
java -jar ParallelHyperQAP.jar esc16g.qap
